apiVersion: v1
kind: Service
metadata:
  name: {{ include "websites.fullname" . }}
  labels:
    {{- include "websites.labels" . | nindent 4 }}
spec:
  {{- range .Values.services }}
  - type: {{ .type }}
    ports:
      - port: {{ .port }}
        targetPort: {{ .targetPort }}
        protocol: {{ .protocol }}
        name: {{ .portName }}
    selector:
      {{- include "websites.selectorLabels" $ | nindent 6 }}
  {{- end }}
