---
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  labels:
    {{- include "websites.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  ports:
    {{- range .ports }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
  selector:
    {{- include "websites.selectorLabels" $ | nindent 4 }}
---
{{- end }}
