{{- if .Values.sopsSecret.enabled }}
apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
  name: {{ .Values.sopsSecret.name | default (include "websites.fullname" .) }}
  namespace: {{ include "websites.namespace" . }}
  labels:
    {{- include "websites.labels" . | nindent 4 }}
    {{- with .Values.sopsSecret.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.sopsSecret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretTemplates:
    {{- range .Values.sopsSecret.secretTemplates }}
    - name: {{ .name }}
      {{- with .labels }}
      labels:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      stringData:
        {{- toYaml .stringData | nindent 8 }}
    {{- end }}
{{- end }}
